on: [push]

env:
  NAME: com.mycompany.my-package
  VERSION: "1.0.${{ github.run_number }}"
  REGISTRY_URL: "https://npm.pkg.github.com/@${{ github.repository_owner }}"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add .npmrc that accepts ${GITHUB_PACKAGES_TOKEN}
        run: echo '//npm.pkg.github.com/:_authToken=${GITHUB_PACKAGES_TOKEN}' > .npmrc

      - name: Create a package called ${{ env.NAME }}
        run: |
          cat > package.json << EOM
          {
            "name": "${{ env.NAME }}",
            "version": "${{ env.VERSION }}",
            "repository": "https://github.com/${{ github.repository }}",
            "description": "My Unity package",
            "main": "index.js"
          }
          EOM

      - name: Add index.js to package
        run: echo 'exports.sayHello = () => { console.log("Hello from ${{ github.repository }}!") }' > index.js

      - name: Build the package
        run: npm pack

      - name: Publish the package
        run: npm publish --registry=${{ env.REGISTRY_URL }}
        env:
          GITHUB_PACKAGES_TOKEN: ${{ github.token }}
